Main svc
akrecev/java-explore-with-me pull request #5
Opened 2023-04-04 13:35 UTC by akrecev

2023-04-05 19:58 UTC, FanaticFiz requested changes

2023-04-05 19:58 UTC, FanaticFiz commented on main/src/main/resources/schema.sql
> +    initiator_id BIGINT,
Не хватает выравнивания

2023-04-05 22:14 UTC, akrecev commented on main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            Long views = 0L;
Полностью согласен)

2023-04-05 22:17 UTC, akrecev commented on main/src/main/java/ru/practicum/exception/BadRequest.java
> +    public BadRequest(String message) {
В топку

2023-04-05 22:17 UTC, akrecev commented on main/src/main/java/ru/practicum/exception/ForbiddenException.java
> +    public ForbiddenException(String message) {
Туда же

2023-04-05 22:18 UTC, akrecev commented on main/src/main/resources/schema.sql
> +    initiator_id BIGINT,
поправил

2023-04-06 19:58 UTC, FanaticFiz approved these changes

2023-04-07 07:36 UTC, merged